### ISSUE TITLE
Open failed: AssertionError:

### ISSUE THREAD

**Issue by SheetJSDev** [python-excel/xlrd#100]
I wish the message were a bit more informative :/

```
$ runxlrd.py 2rows ootest_definedname_import_biff8_12.xls

=== File: ootest_definedname_import_biff8_12.xls ===
*** Open failed: AssertionError:
Traceback (most recent call last):
  File "/usr/local/bin/runxlrd.py", line 332, in main
    ragged_rows=options.ragged_rows,
  File "/Library/Python/2.7/site-packages/xlrd/__init__.py", line 435, in open_workbook
    ragged_rows=ragged_rows,
  File "/Library/Python/2.7/site-packages/xlrd/book.py", line 116, in open_workbook_xls
    bk.parse_globals()
  File "/Library/Python/2.7/site-packages/xlrd/book.py", line 1198, in parse_globals
    self.names_epilogue()
  File "/Library/Python/2.7/site-packages/xlrd/book.py", line 997, in names_epilogue
    evaluate_name_formula(self, nobj, namex, blah=blah)
  File "/Library/Python/2.7/site-packages/xlrd/formula.py", line 841, in evaluate_name_formula
    assert len(stack) >= 2
AssertionError
```

File: http://www.openoffice.org/sc/testdocs/definedname_import_biff8_12.xls

**Comment by cjw296** [comment]
Sorry, going to need a pull request with unit test to verify in order to fix.
Closing in the meantime.
