### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by SheetJSDev** [python-excel/xlrd#101]
```
*** Open failed: IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/runxlrd.py", line 332, in main
    ragged_rows=options.ragged_rows,
  File "/Library/Python/2.7/site-packages/xlrd/__init__.py", line 416, in open_workbook
    ragged_rows=ragged_rows,
  File "/Library/Python/2.7/site-packages/xlrd/xlsx.py", line 791, in open_workbook_2007_xml
    x12sheet.process_stream(zflo, heading)
  File "/Library/Python/2.7/site-packages/xlrd/xlsx.py", line 528, in own_process_stream
    self_do_row(elem)
  File "/Library/Python/2.7/site-packages/xlrd/xlsx.py", line 667, in do_row
    value = self.sst[int(tvalue)]
IndexError: list index out of range
```

https://www.dropbox.com/s/bcri2zay2kehxqo/self_evaluation_report_2014-05-19.xlsx

**Comment by HEdingfield** [comment]
What's the status on this? Any idea why it hasn't been merged in yet?

**Comment by sjmachin** [comment]
I have merged the PR from #97 ...

**Comment by HEdingfield** [comment]
Awesome, I think that resolves this issue. Do we have an idea with xlrd 0.9.4 (or whichever) is going to be released?

**Comment by sjmachin** [comment]
@cjw296 ?

**Comment by cjw296** [comment]
Done.

**Comment by HEdingfield** [comment]
Works great! I believe you can close this issue now.
