### ISSUE TITLE
IndexError: array index out of range

### ISSUE THREAD

**Issue by seecmb** [python-excel/xlrd#113]
Error:

```
Traceback (most recent call last):
  File "/usr/local/bin/runxlrd.py", line 414, in <module>
    main(av)
  File "/usr/local/bin/runxlrd.py", line 356, in main
    show(bk, 2)
  File "/usr/local/bin/runxlrd.py", line 205, in show
    show_row(bk, sh, nrows-1, colrange, printit)
  File "/usr/local/bin/runxlrd.py", line 73, in show_row
    for colx, ty, val, _unused in get_row_data(bk, sh, rowx, colrange):
  File "/usr/local/bin/runxlrd.py", line 83, in get_row_data
    cty = ctys[colx]
IndexError: array index out of range
```

**Comment by cjw296** [comment]
Looks like the pull request has been merged, so should be fixed in 1.0.1
