### ISSUE TITLE
AssertionError:  assert _unused_i == nstrings - 1

### ISSUE THREAD

**Issue by facetoe** [python-excel/xlrd#132]
Hi, I get this AssertionError when trying to read an .xls file:

    WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
    Traceback (most recent call last):
      File "/home/will/git/sync-scripts/test.py", line 9, in <module>
        d = open_workbook('/home/will/git/sync-scripts/test_school/STUDENT_MEDICAL_SEQTA.xls')
      File "/usr/local/lib/python2.7/dist-packages/xlrd/__init__.py", line 435, in open_workbook
        ragged_rows=ragged_rows,
      File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 116, in open_workbook_xls
        bk.parse_globals()
      File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1158, in parse_globals
        self.handle_sst(data)
      File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1129, in handle_sst
        self._sharedstrings, rt_runlist = unpack_SST_table(strlist, uniquestrings)
      File "/usr/local/lib/python2.7/dist-packages/xlrd/book.py", line 1418, in unpack_SST_table
        assert _unused_i == nstrings - 1
    AssertionError

Any idea how I can fix this?

**Comment by facetoe** [comment]
My bad, the file was filled with junk.
