### ISSUE TITLE
CompDocError: Workbook corruption: seen[3] == 4

### ISSUE THREAD

**Issue by tonal** [python-excel/xlrd#149]
Steps:
```
$ wget -O err.xls http://santshop.ru/prices/download/710/
$ runxlrd.py hdr err.xls
=== File: err.xls ===
_locate_stream(Workbook): seen
    0  5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
   20  4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
  360= 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
  380  4 4 4 4 3 2 2 2 2 
*** Open failed: CompDocError: Workbook corruption: seen[3] == 4
Traceback (most recent call last):
  File "/home/tonal/.local/bin/runxlrd.py", line 332, in main
    ragged_rows=options.ragged_rows,
  File "/home/tonal/.local/lib/python2.7/site-packages/xlrd/__init__.py", line 435, in open_workbook
    ragged_rows=ragged_rows,
  File "/home/tonal/.local/lib/python2.7/site-packages/xlrd/book.py", line 87, in open_workbook_xls
    ragged_rows=ragged_rows,
  File "/home/tonal/.local/lib/python2.7/site-packages/xlrd/book.py", line 592, in biff2_8_load
    cd.locate_named_stream(UNICODE_LITERAL(qname))
  File "/home/tonal/.local/lib/python2.7/site-packages/xlrd/compdoc.py", line 390, in locate_named_stream
    d.tot_size, qname, d.DID+6)
  File "/home/tonal/.local/lib/python2.7/site-packages/xlrd/compdoc.py", line 418, in _locate_stream
    raise CompDocError("%s corruption: seen[%d] == %d" % (qname, s, self.seen[s]))
CompDocError: Workbook corruption: seen[3] == 4
```
But LibreOffice 5 open this file

**Comment by cjw296** [comment]
Where did the file come from?

**Comment by tonal** [comment]
I do not known.
All *.xls files from http://santshop.ru/prices/ has the same error.

**Comment by cjw296** [comment]
Looks like a corrupt set of files, contact the producers and get them to fix.

**Comment by JonWel** [comment]
I'm also having this issue with files generated in a web page.
Opening the file and saving it with OpenOffice (in .xls) removes the error.
As both Excel and OpenOffice seems to read this perfectly fine, I think there is a kind of legit format that is not appreciated by xlrd.

**Comment by dsw0214** [comment]
I also encountered the same problem, sympathetic solution

**Comment by laurentperrinet** [comment]
Works by commenting lines around 426 in ``xlrd/compdoc.py``

Would it be possible to give the user the option to read such "corrupt" files?
