### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by gandriyko** [python-excel/xlrd#227]
When I trying to open file via xlrd:
```python 
book = xlrd.open_workbook('e.xls', encoding_override='cp1251')
```
I receive error:
 
```python
WARNING *** file size (7267889) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
Traceback (most recent call last):
  File "./temp", line 35, in <module>
    book = xlrd.open_workbook('e.xls', encoding_override='cp1251')
  File "/home/andrew/www/realavto/lib/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "/home/andrew/www/realavto/lib/xlrd/book.py", line 119, in open_workbook_xls
    bk.get_sheets()
  File "/home/andrew/www/realavto/lib/xlrd/book.py", line 719, in get_sheets
    self.get_sheet(sheetno)
  File "/home/andrew/www/realavto/lib/xlrd/book.py", line 710, in get_sheet
    sh.read(self)
  File "/home/andrew/www/realavto/lib/xlrd/sheet.py", line 818, in read
    self_put_cell(rowx, colx, XL_CELL_TEXT, strg, xf_index)
  File "/home/andrew/www/realavto/lib/xlrd/sheet.py", line 709, in put_cell_unragged
    assert 1 <= nr <= self.utter_max_rows
AssertionError


```

**Comment by gandriyko** [comment]
This file:
[test.zip](https://github.com/python-excel/xlrd/files/1290667/test.zip)

**Comment by Hasenigel** [comment]
Hi gandriyko, how did you solve this issue? I have a very similar error message

**Comment by gandriyko** [comment]
Hello! No, I didn't.
just comment line  **assert 1 <= nr <= self.utter_max_rows** and it works.

**Comment by Hasenigel** [comment]
Unfortunately not, no. I found a different solution for the problem i had

**Comment by cjw296** [comment]
Glad to hear you found a solution.
