### ISSUE TITLE
xlrd can't open files generated by test/fake data website

### ISSUE THREAD

**Issue by xmo-odoo** [python-excel/xlrd#285]
Using http://generatedata.com to generate an excel file and trying to open that file with xlrd results in the following error:
```
_locate_stream(Workbook): seen
    0  5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
   20  4 4 4 4 4 4 4 4 4 4 4 4 4 3 2 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.6/site-packages/xlrd/__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "lib/python3.6/site-packages/xlrd/book.py", line 87, in open_workbook_xls
    ragged_rows=ragged_rows,
  File "lib/python3.6/site-packages/xlrd/book.py", line 633, in biff2_8_load
    cd.locate_named_stream(UNICODE_LITERAL(qname))
  File "lib/python3.6/site-packages/xlrd/compdoc.py", line 398, in locate_named_stream
    d.tot_size, qname, d.DID+6)
  File "lib/python3.6/site-packages/xlrd/compdoc.py", line 426, in _locate_stream
    raise CompDocError("%s corruption: seen[%d] == %d" % (qname, s, self.seen[s]))
xlrd.compdoc.CompDocError: Workbook corruption: seen[2] == 4
```
The excel export is [apparently](https://github.com/benkeen/generatedata/tree/master/plugins/exportTypes/Excel) handle by [PHPExcel](https://github.com/PHPOffice/PHPExcel)

Although generating new ones with different parameters seems to yield the same issue, this is the specific file I initially got (zipped because github does not want to upload xls files even though it supports xlsx...) [oddfile.xls.zip](https://github.com/python-excel/xlrd/files/2176760/oddfile.xls.zip)

**Comment by cjw296** [comment]
Sorry, not really interested.
