### ISSUE TITLE
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x20 in position

### ISSUE THREAD

**Issue by tierneykev** [python-excel/xlrd#288]
Ran into this issue with a file downloaded from a client site. The xls file is created using GrapeCity's Spreadsheet Builder (https://www.grapecity.com/en/spread). If I opened the file in excel, didn't even have to save the file, just by opening the file the issue would go awayThat doesn't really work when you're trying to automate the process

Full Error
>Traceback (most recent call last):
  File "testing.py", line 249, in <module>
    main()
  File "testing.py", line 189, in main
    data = pd.read_excel(f)
  File "C:\Python3\lib\site-packages\pandas\util\_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\pandas\io\excel.py", line 230, in read_excel
    io = ExcelFile(io, engine=engine)
  File "C:\Python3\lib\site-packages\pandas\io\excel.py", line 292, in __init__
    self.book = xlrd.open_workbook(file_contents=data)
  File "C:\Python3\lib\site-packages\xlrd\__init__.py", line 162, in open_workbook
    ragged_rows=ragged_rows,
  File "C:\Python3\lib\site-packages\xlrd\book.py", line 116, in open_workbook_xls
    bk.parse_globals()
  File "C:\Python3\lib\site-packages\xlrd\book.py", line 1221, in parse_globals
    self.handle_writeaccess(data)
  File "C:\Python3\lib\site-packages\xlrd\book.py", line 1186, in handle_writeaccess
    strg = unpack_unicode(data, 0, lenlen=2)
  File "C:\Python3\lib\site-packages\xlrd\biffh.py", line 283, in unpack_unicode
    strg = unicode(rawstrg, 'utf_16_le')
  File "C:\Python3\lib\site-packages\xlrd\timemachine.py", line 30, in <lambda>
    unicode = lambda b, enc: b.decode(enc)
  File "C:\Python3\lib\encodings\utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x20 in position 108: truncated data

After trying to figure out a workaround all day I finally decided to see if I could find an issue with the xlrd code

uncommenting line 283 in biffh, I got this back

nchars=86 pos=3 rawstrg=b'G\x00r\x00a\x00p\x00e\x00C\x00i\x00t\x00y\x00 \x00S\x00p\x00r\x00e\x00a\x00d\x00B\x00u\x00i\x00l\x00d\x00e\x00r\x00 \x00 \x0
0 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 \x00 '

I noticed the extra space at the end of the rawstring. 

Modifying Line 284 from
`strg = unicode(rawstrg, 'utf_16_le')`

To 
`strg = unicode(rawstrg.strip(), 'utf_16_le')`

has resolved the issue with my file

**Comment by cjw296** [comment]
The source file is invalid, I'm afraid you'll need to get them to fix it.
