### ISSUE TITLE
read_excel prompts error as IndexError: list index out of range

### ISSUE THREAD

**Issue by chavan-vjti** [python-excel/xlrd#290]
I'm working on Windows 10 and Python 2.7 .

When I execute following command in python
```python
df_1 = df_1 = pd.read_excel("\\\\10.10.2.51\\DataShare_Magic9\\Insight_Projects_2018\\Insight Project_2_Co-viewing\\Program\\20180216_genre.xlsx")
```
I get the following error,
```python
Traceback (most recent call last):
  File "C:\Miniconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-3703548ede6e>", line 1, in <module>
    df_1 = pd.read_excel("\\\\10.10.2.51\\DataShare_Magic9\\Insight_Projects_2018\\Insight Project_2_Co-viewing\\Program\\20180216_genre.xlsx", header=None)
  File "C:\Miniconda2\lib\site-packages\pandas\util\_decorators.py", line 177, in wrapper
    return func(*args, **kwargs)
  File "C:\Miniconda2\lib\site-packages\pandas\util\_decorators.py", line 177, in wrapper
    return func(*args, **kwargs)
  File "C:\Miniconda2\lib\site-packages\pandas\io\excel.py", line 307, in read_excel
    io = ExcelFile(io, engine=engine)
  File "C:\Miniconda2\lib\site-packages\pandas\io\excel.py", line 394, in __init__
    self.book = xlrd.open_workbook(self._io)
  File "C:\Miniconda2\lib\site-packages\xlrd\__init__.py", line 143, in open_workbook
    ragged_rows=ragged_rows,
  File "C:\Miniconda2\lib\site-packages\xlrd\xlsx.py", line 837, in open_workbook_2007_xml
    x12sheet.process_stream(zflo, heading)
  File "C:\Miniconda2\lib\site-packages\xlrd\xlsx.py", line 548, in own_process_stream
    self_do_row(elem)
  File "C:\Miniconda2\lib\site-packages\xlrd\xlsx.py", line 708, in do_row
    value = self.sst[int(tvalue)]
IndexError: list index out of range
```
I'm in need of expert advice.

Thank you!

**Comment by cjw296** [comment]
Please use https://openpyxl.readthedocs.io/en/stable/ for xlsx.

Please see https://github.com/pandas-dev/pandas/issues/26487 for where
this needs to be fixed.
