### ISSUE TITLE
XLRD fails to open valid excel (.xls) file

### ISSUE THREAD

**Issue by willtownes** [python-excel/xlrd#85]
Bug was observed in following environments:
xlrd 0.9.2
windows 7/ python 2.7.5
linux (redhat)/ python 2.4
I can email you the file that is causing the failure, if that helps

Traceback (most recent call last):
  File "xlrdFail.py", line 8, in <module>
    main()
  File "xlrdFail.py", line 4, in main
    book = xlrd.open_workbook('Products_Export_Non_Lighting.xls')
  File "C:\Python27\lib\site-packages\xlrd\__init__.py", line 435, in open_workbook
    ragged_rows=ragged_rows,
  File "C:\Python27\lib\site-packages\xlrd\book.py", line 87, in open_workbook_xls
    ragged_rows=ragged_rows,
  File "C:\Python27\lib\site-packages\xlrd\book.py", line 615, in biff2_8_load
    cd = compdoc.CompDoc(self.filestr, logfile=self.logfile)
  File "C:\Python27\lib\site-packages\xlrd\compdoc.py", line 162, in __init__
    raise CompDocError("MSAT extension: invalid sector id: %d" % sid)
CompDocError: MSAT extension: invalid sector id: -4

**Comment by larserikh** [comment]
Some of our clients regularly upload files having this issue and I know that the fix proposed by @xiaods works. It definitely think it should be merged in.

**Comment by cjw296** [comment]
Please can you submit a pull request with the above changes and I'll get it merged.

**Comment by xiaods** [comment]
@cjw296  i have do it already. https://github.com/python-excel/xlrd/pull/98

**Comment by cjw296** [comment]
Merged.
