### ISSUE TITLE
xlrd 0.9.3 open_workbook fails for xlsm

### ISSUE THREAD

**Issue by nitram009** [python-excel/xlrd#89]
Hi, i am runnig python 2.7 and xlrd 0.9.3 and i have encountered this error:

C:\app>python __tmp_app_run.py Test.xlsm
Traceback (most recent call last):
  File "__tmp_app_run.py", line 5, in <module>
    a = Analyser(f)
  File "C:\app\analyser.py", line 30, in __init__
    self.book = xlrd.open_workbook(file_contents=fileObject.read(),on_demand=True)
  File "C:\Python27\lib\site-packages\xlrd\__init__.py", line 416, in open_workbook
    ragged_rows=ragged_rows,
  File "C:\Python27\lib\site-packages\xlrd\xlsx.py", line 791, in open_workbook_2007_xml
    x12sheet.process_stream(zflo, heading)
  File "C:\Python27\lib\site-packages\xlrd\xlsx.py", line 533, in own_process_stream
    self.do_merge_cell(elem)
  File "C:\Python27\lib\site-packages\xlrd\xlsx.py", line 573, in do_merge_cell
    first_cell_ref, last_cell_ref = ref.split(':')
ValueError: need more than 1 value to unpack

When i use xlrd 0.9.2 it works fine. When i save the same file as xls it works.

Regards, Martin

**Comment by PythonNewbie0215** [comment]
Hi, I am facing the same problem while reading it using pandas. Could you please share the fix with me

**Comment by jmcnamara** [comment]
@PythonNewbie0215 

PR #120 includes a fix for this issue.

**Comment by cjw296** [comment]
@jmcnamara - will merge #120 now!
