### ISSUE TITLE
assert (data_len - endpos) in (0, 1)

### ISSUE THREAD

**Issue by gatang** [python-excel/xlrd#93]
I try xlrd, find following error:

```
*** Open failed: AssertionError:
Traceback (most recent call last):
  File "/usr/local/bin/runxlrd.py", line 332, in main
    ragged_rows=options.ragged_rows,
  File "/Library/Python/2.7/site-packages/xlrd/__init__.py", line 435, in open_workbook
    ragged_rows=ragged_rows,
  File "/Library/Python/2.7/site-packages/xlrd/book.py", line 119, in open_workbook_xls
    bk.get_sheets()
  File "/Library/Python/2.7/site-packages/xlrd/book.py", line 678, in get_sheets
    self.get_sheet(sheetno)
  File "/Library/Python/2.7/site-packages/xlrd/book.py", line 669, in get_sheet
    sh.read(self)
  File "/Library/Python/2.7/site-packages/xlrd/sheet.py", line 1090, in read
    self.handle_note(data, txos)
  File "/Library/Python/2.7/site-packages/xlrd/sheet.py", line 1956, in handle_note
    assert (data_len - endpos) in (0, 1)
AssertionError
```

**Comment by cjw296** [comment]
We'd need a lot more to go on to be able to help. Closing as out of date.
If you can reproduce, please open a new issue and include a link to the problematic file.

I'll be honest though: unless you follow that up with a pull request that includes unit tests, it's unlikely to see any progress...
